//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBERVET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int idAdm { get; set; }
        public string nombreAdm { get; set; }
        public string apellidoAdm { get; set; }
        public Nullable<int> iddistrito { get; set; }
        public int dniAdm { get; set; }
        public string emailAdm { get; set; }
        public string pwdAdm { get; set; }
    
        public virtual tb_distrito tb_distrito { get; set; }
    }
}
