//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBERVET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int CarritoID { get; set; }
        public string Identificador { get; set; }
        public Nullable<int> idusuario { get; set; }
        public int id_prod { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual tb_producto tb_producto { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
