//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBERVET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_producto()
        {
            this.Carrito = new HashSet<Carrito>();
            this.tb_pedidoDeta = new HashSet<tb_pedidoDeta>();
        }
    
        public int id_prod { get; set; }
        public string descripcionSimple_prod { get; set; }
        public decimal precio_prod { get; set; }
        public int stock_prod { get; set; }
        public string serie_prod { get; set; }
        public string marca_prod { get; set; }
        public Nullable<int> id_cate { get; set; }
        public Nullable<int> id_prove { get; set; }
        public string descripcionHTML_prod { get; set; }
        public string foto1_prod { get; set; }
        public string foto2_prod { get; set; }
        public string foto3_prod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito> Carrito { get; set; }
        public virtual tb_categoria tb_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedidoDeta> tb_pedidoDeta { get; set; }
        public virtual tb_proveedor tb_proveedor { get; set; }
    }
}
