//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBERVET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedidoCabe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pedidoCabe()
        {
            this.tb_pedidoDeta = new HashSet<tb_pedidoDeta>();
        }
    
        public int id_pedido { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public decimal total_pedido { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        public virtual tb_estado tb_estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedidoDeta> tb_pedidoDeta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
