//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIBERVET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.Carrito = new HashSet<Carrito>();
            this.MASCOTA = new HashSet<MASCOTA>();
            this.tb_pedidoCabe = new HashSet<tb_pedidoCabe>();
        }
    
        public int idusuario { get; set; }
        public string dni { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public Nullable<int> IdDistritos { get; set; }
        public Nullable<int> IdTipoUsuarios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito> Carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASCOTA> MASCOTA { get; set; }
        public virtual tb_distrito tb_distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedidoCabe> tb_pedidoCabe { get; set; }
        public virtual TIPOUSUARIO TIPOUSUARIO { get; set; }
    }
}
